#!/usr/bin/env bash
set -e

# Change to the repository root directory
cd "$(dirname "$(readlink -f "$BASH_SOURCE")")/.."

# Generate the AUTHORS file based on git history
cat <<EOF > AUTHORS
# File @generated by hack/generate-authors.sh. DO NOT EDIT.
# This file lists all contributors to the repository.
# See hack/generate-authors.sh to make modifications.

$(git log --format='%aN <%aE>' | sort -u)
EOF
